### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by gregtampa** [legitbs/scorebot#3]
`rails aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'uglifier'.
Gem Load Error is: wrong argument type Class (expected Module)
Backtrace for gem load error is:
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:23:in `include'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:23:in `block (2 levels) in <top (required)>'
`

i googled and tried some stuff... any info on this?
might be my ruby version?

**Comment by vito-lbs** [comment]
Never had to troubleshoot that one before. There's a `docker-compose.yml` that spools everything for production.
